### ISSUE TITLE
Cannot remove fake players

### ISSUE THREAD

**Issue by ading2210** [spigotplugins/fakeplayer#24]
Creating them works fine, but running /fakeplayer remove [player] does not work. However removing a fake player that does not exists does not give an error for some reason.

![image](https://user-images.githubusercontent.com/71154407/103823573-3484d800-5027-11eb-81da-1f432ed1f373.png)

I am using the latest version of the plugin with Paper v202

**Comment by kheeong** [comment]
Same issues using on spigot

**Comment by xSlart01x** [comment]
I think it was a little distraction.
The error is obviously caused by [this if](https://github.com/spigotplugins/fakeplayer/blob/98a89447251a80892773aba20511ebcf73ce377a/fakeplayer-plugin/src/main/java/io/github/portlek/fakeplayer/commands/FakePlayerCommand.java#L73) that should be negated.
Hope this helps :)

**Comment by portlek** [comment]
@kheeong @ading2210 could you try the latest release to confirm the solution?

**Comment by ading2210** [comment]
![image](https://user-images.githubusercontent.com/71154407/110008710-e14e9f00-7cd0-11eb-8596-10e65d74c6d6.png)
Works fine now!
